import React, { useState, useEffect } from 'react';
import { Formik, Form, Field, ErrorMessage, FormikHelpers } from 'formik';
import { useNavigate } from 'react-router-dom';
import { Card } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../components/ui/tabs';
import { 
  Building, 
  FileText, 
  Phone, 
  Landmark, 
  CheckCircle,
  Upload,
  RefreshCw,
  Settings,
  Loader2
} from 'lucide-react';
import { societySetupValidationSchema } from '../../utils/validationSchemas/societySetupValidation';
import { generateSocietyCode, createSociety, updateSociety, Society } from '../../apis/societyApi';
import { toast } from 'sonner';

interface SocietyFormValues {
  // Basic Information
  societyName: string;
  societyCode: string;
  description: string;
  logo: File | null;

  // Project Details
  projectType: string;
  totalUnits: number | string;
  totalBlocks: number | string;
  totalFloors: number | string;
  carpetAreaRange: string;
  projectStartDate: string;
  completionDate: string;
  developerName: string;

  // Contact Information
  contactPersonName: string;
  contactNumber: string;
  email: string;
  alternateContact: string;
  address: string;
  city: string;
  state: string;
  pincode: string;

  // Legal Documents
  reraNumber: string;
  reraCertificate: File | null;
  reraExpiryDate: string;
  fireNocNumber: string;
  fireNocDocument: File | null;
  fireNocValidityDate: string;
  buCertificateNumber: string;
  buCertificate: File | null;
  buIssueDate: string;
  liftLicenceNumber: string;
  liftLicenceDocument: File | null;
  liftLicenceExpiryDate: string;

  // Financial Setup
  bankName: string;
  accountNumber: string;
  accountHolderName: string;
  ifscCode: string;
  branchName: string;
  branchAddress: string;
  gstNumber: string;
  gstCertificate: File | null;
  panNumber: string;
  tanNumber: string;
  fyStartMonth: string;
  currentFinancialYear: string;

  // Additional Settings
  status: string;
  maintenanceBillingCycle: string;
  registeredMembersCount: number | string;
}

const getInitialValues = (autoGeneratedCode: string, initialData?: Society): SocietyFormValues => {
  if (initialData) {
    // Format dates for input fields (YYYY-MM-DD)
    const formatDate = (dateString?: string) => {
      if (!dateString) return '';
      const date = new Date(dateString);
      return date.toISOString().split('T')[0];
    };

    return {
      societyName: initialData.societyName || '',
      societyCode: initialData.societyCode || autoGeneratedCode,
      description: initialData.description || '',
      logo: null, // Files need to be re-uploaded
      projectType: initialData.projectType || 'Residential',
      totalUnits: initialData.totalUnits || '',
      totalBlocks: initialData.totalBlocks || '',
      totalFloors: initialData.totalFloors || '',
      carpetAreaRange: initialData.carpetAreaRange || '',
      projectStartDate: formatDate(initialData.projectStartDate),
      completionDate: formatDate(initialData.completionDate),
      developerName: initialData.developerName || '',
      contactPersonName: initialData.contactPersonName || '',
      contactNumber: initialData.contactNumber || '',
      email: initialData.email || '',
      alternateContact: initialData.alternateContact || '',
      address: initialData.address?.street || '',
      city: initialData.address?.city || '',
      state: initialData.address?.state || '',
      pincode: initialData.address?.pincode || '',
      reraNumber: initialData.legalDocuments?.rera?.number || '',
      reraCertificate: null,
      reraExpiryDate: formatDate(initialData.legalDocuments?.rera?.expiryDate),
      fireNocNumber: initialData.legalDocuments?.fireNoc?.number || '',
      fireNocDocument: null,
      fireNocValidityDate: formatDate(initialData.legalDocuments?.fireNoc?.validityDate),
      buCertificateNumber: initialData.legalDocuments?.buCertificate?.number || '',
      buCertificate: null,
      buIssueDate: formatDate(initialData.legalDocuments?.buCertificate?.issueDate),
      liftLicenceNumber: initialData.legalDocuments?.liftLicence?.number || '',
      liftLicenceDocument: null,
      liftLicenceExpiryDate: formatDate(initialData.legalDocuments?.liftLicence?.expiryDate),
      bankName: initialData.bankDetails?.bankName || '',
      accountNumber: initialData.bankDetails?.accountNumber || '',
      accountHolderName: initialData.bankDetails?.accountHolderName || '',
      ifscCode: initialData.bankDetails?.ifscCode || '',
      branchName: initialData.bankDetails?.branchName || '',
      branchAddress: initialData.bankDetails?.branchAddress || '',
      gstNumber: initialData.taxInformation?.gstNumber || '',
      gstCertificate: null,
      panNumber: initialData.taxInformation?.panNumber || '',
      tanNumber: initialData.taxInformation?.tanNumber || '',
      fyStartMonth: initialData.financialYear?.fyStartMonth || 'April',
      currentFinancialYear: initialData.financialYear?.currentFinancialYear || '2024-2025',
      status: initialData.status || 'Pending',
      maintenanceBillingCycle: initialData.maintenanceBillingCycle || 'Monthly',
      registeredMembersCount: initialData.registeredMembersCount || '',
    };
  }

  // Default values for create mode
  return {
  societyName: '',
  societyCode: autoGeneratedCode,
  description: '',
  logo: null,
  projectType: 'Residential',
  totalUnits: '',
  totalBlocks: '',
  totalFloors: '',
  carpetAreaRange: '',
  projectStartDate: '',
  completionDate: '',
  developerName: '',
  contactPersonName: '',
  contactNumber: '',
  email: '',
  alternateContact: '',
  address: '',
  city: '',
  state: '',
  pincode: '',
  reraNumber: '',
  reraCertificate: null,
  reraExpiryDate: '',
  fireNocNumber: '',
  fireNocDocument: null,
  fireNocValidityDate: '',
  buCertificateNumber: '',
  buCertificate: null,
  buIssueDate: '',
  liftLicenceNumber: '',
  liftLicenceDocument: null,
  liftLicenceExpiryDate: '',
  bankName: '',
  accountNumber: '',
  accountHolderName: '',
  ifscCode: '',
  branchName: '',
  branchAddress: '',
  gstNumber: '',
  gstCertificate: null,
  panNumber: '',
  tanNumber: '',
  fyStartMonth: 'April',
  currentFinancialYear: '2024-2025',
  status: 'Pending',
  maintenanceBillingCycle: 'Monthly',
  registeredMembersCount: '',
  };
};

const FileUploadField: React.FC<{
  name: string;
  label: string;
  value: File | null;
  onChange: (file: File | null) => void;
  error?: string;
  touched?: boolean;
  required?: boolean;
  existingFileUrl?: string;
}> = ({ name, label, value, onChange, error, touched, required = false, existingFileUrl }) => {
  return (
    <div>
      <label htmlFor={name} className="block text-sm font-semibold text-gray-900 mb-2">
        {label} {required && <span className="text-red-500">*</span>}
      </label>
      
      {/* Show existing file if available */}
      {existingFileUrl && !value && (
        <div className="mb-2 p-3 bg-blue-50 border border-blue-200 rounded-lg">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-blue-600" />
              <span className="text-sm text-blue-900 font-medium">Current file uploaded</span>
            </div>
            <a 
              href={existingFileUrl} 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-sm text-blue-600 hover:text-blue-800 underline flex items-center gap-1"
            >
              View File
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
              </svg>
            </a>
          </div>
          <p className="text-xs text-gray-600 mt-1">Upload a new file to replace this one</p>
        </div>
      )}
      
      <label className="cursor-pointer block">
        <div className={`w-full px-4 py-3 border-2 border-dashed rounded-lg hover:border-blue-500 transition-colors flex items-center justify-center ${
          error && touched ? 'border-red-500' : 'border-gray-300'
        }`}>
          <Upload className="w-5 h-5 text-gray-400 mr-2" />
          <span className="text-sm text-gray-600">
            {value ? (value as File).name : existingFileUrl ? `Replace ${label}` : `Upload ${label}`}
          </span>
        </div>
        <input
          type="file"
          id={name}
          name={name}
          className="hidden"
          accept=".pdf,.jpg,.jpeg,.png"
          onChange={(event) => {
            const file = event.currentTarget.files?.[0] || null;
            onChange(file);
          }}
        />
      </label>
      {error && touched && <div className="mt-1 text-sm text-red-500">{error}</div>}
    </div>
  );
};

interface SocietySetupFormProps {
  mode?: 'create' | 'edit';
  societyId?: string;
  initialData?: Society;
}

export const SocietySetupForm: React.FC<SocietySetupFormProps> = ({ 
  mode = 'create',
  societyId,
  initialData 
}) => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('basic');
  const [isGeneratingCode, setIsGeneratingCode] = useState(false);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');

  // Auto-generate code on component mount (only in create mode)
  useEffect(() => {
    if (mode === 'edit' && initialData) {
      setAutoGeneratedCode(initialData.societyCode);
      return;
    }

    const autoGenerateCode = async () => {
      try {
        const { societyCode } = await generateSocietyCode();
        setAutoGeneratedCode(societyCode);
      } catch (error: any) {
        console.error('Error auto-generating code:', error);
        // Generate a fallback code if API fails
        const year = new Date().getFullYear();
        const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
        setAutoGeneratedCode(`SOC-${year}-${random}`);
      }
    };

    autoGenerateCode();
  }, [mode, initialData]);

  const handleGenerateCode = async (setFieldValue: any) => {
    setIsGeneratingCode(true);
    try {
      const { societyCode } = await generateSocietyCode();
      setFieldValue('societyCode', societyCode);
      toast.success('Society code generated successfully');
    } catch (error: any) {
      console.error('Error generating code:', error);
      toast.error(error.message || 'Failed to generate society code');
      // Generate fallback code
      const year = new Date().getFullYear();
      const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
      setFieldValue('societyCode', `SOC-${year}-${random}`);
    } finally {
      setIsGeneratingCode(false);
    }
  };

  const handleSubmit = async (
    values: SocietyFormValues,
    { setSubmitting }: FormikHelpers<SocietyFormValues>
  ) => {
    try {
      // Prepare data for API
      const societyData = {
        societyName: values.societyName,
        societyCode: values.societyCode,
        description: values.description,
        projectType: values.projectType,
        totalUnits: values.totalUnits,
        totalBlocks: values.totalBlocks || 0,
        totalFloors: values.totalFloors || 0,
        carpetAreaRange: values.carpetAreaRange,
        projectStartDate: values.projectStartDate,
        completionDate: values.completionDate,
        developerName: values.developerName,
        contactPersonName: values.contactPersonName,
        contactNumber: values.contactNumber,
        email: values.email,
        alternateContact: values.alternateContact,
        address: {
          street: values.address,
          city: values.city,
          state: values.state,
          pincode: values.pincode,
        },
        legalDocuments: {
          rera: {
            number: values.reraNumber,
            expiryDate: values.reraExpiryDate,
          },
          fireNoc: {
            number: values.fireNocNumber,
            validityDate: values.fireNocValidityDate,
          },
          buCertificate: {
            number: values.buCertificateNumber,
            issueDate: values.buIssueDate,
          },
          liftLicence: {
            number: values.liftLicenceNumber,
            expiryDate: values.liftLicenceExpiryDate,
          },
        },
        bankDetails: {
          bankName: values.bankName,
          accountNumber: values.accountNumber,
          accountHolderName: values.accountHolderName,
          ifscCode: values.ifscCode,
          branchName: values.branchName,
          branchAddress: values.branchAddress,
        },
        taxInformation: {
          gstNumber: values.gstNumber,
          panNumber: values.panNumber,
          tanNumber: values.tanNumber,
        },
        financialYear: {
          fyStartMonth: values.fyStartMonth,
          currentFinancialYear: values.currentFinancialYear,
        },
        status: values.status,
        maintenanceBillingCycle: values.maintenanceBillingCycle,
        registeredMembersCount: values.registeredMembersCount || 0,
      };

      // Prepare files (only include files that were selected)
      const files: Record<string, File> = {};
      if (values.logo) files.logo = values.logo as File;
      if (values.reraCertificate) files.reraCertificate = values.reraCertificate as File;
      if (values.fireNocDocument) files.fireNocDocument = values.fireNocDocument as File;
      if (values.buCertificate) files.buCertificate = values.buCertificate as File;
      if (values.liftLicenceDocument) files.liftLicenceDocument = values.liftLicenceDocument as File;
      if (values.gstCertificate) files.gstCertificate = values.gstCertificate as File;

      // Submit to API
      if (mode === 'edit' && societyId) {
        await updateSociety(societyId, societyData, files);
        toast.success('Society/Project updated successfully!');
      } else {
      await createSociety(societyData, files);
      toast.success('Society/Project created successfully!');
      }
      
      navigate('/societies');
    } catch (error: any) {
      console.error('Error submitting form:', error);
      toast.error(error.message || `Failed to ${mode === 'edit' ? 'update' : 'create'} society/project. Please try again.`);
    } finally {
      setSubmitting(false);
    }
  };

  const tabs = [
    { value: 'basic', label: 'Basic Info', icon: Building },
    { value: 'project', label: 'Project Details', icon: Building },
    { value: 'contact', label: 'Contact', icon: Phone },
    { value: 'legal', label: 'Legal Docs', icon: FileText },
    { value: 'financial', label: 'Financial', icon: Landmark },
    { value: 'settings', label: 'Settings', icon: Settings },
  ];

  return (
    <div className="container mx-auto p-6 max-w-7xl">
      <Card className="bg-white shadow-lg">
        <div className="p-8">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-gray-900 mb-2">
              {mode === 'edit' ? 'Edit Society & Project' : 'Society & Project Setup'}
            </h1>
            <p className="text-gray-600">
              {mode === 'edit' 
                ? 'Update society/project information' 
                : 'Create and manage societies and projects with comprehensive details'}
            </p>
          </div>

          <Formik
            initialValues={getInitialValues(autoGeneratedCode, initialData)}
            enableReinitialize={true}
            validationSchema={societySetupValidationSchema}
            onSubmit={handleSubmit}
            validateOnChange={true}
            validateOnBlur={true}
          >
            {({ values, errors, touched, isSubmitting, setFieldValue }) => (
              <Form>
                <Tabs value={activeTab} onValueChange={setActiveTab}>
                  {/* Tab Navigation */}
                  <TabsList className="grid w-full grid-cols-6 mb-8">
                    {tabs.map((tab) => {
                      const Icon = tab.icon;
                      return (
                        <TabsTrigger
                          key={tab.value}
                          value={tab.value}
                          className="flex items-center gap-2"
                        >
                          <Icon className="w-4 h-4" />
                          <span className="hidden md:inline">{tab.label}</span>
                        </TabsTrigger>
                      );
                    })}
                  </TabsList>

                  {/* Tab 1: Basic Information */}
                  <TabsContent value="basic" className="space-y-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Basic Information</h2>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      {/* Society Name */}
                      <div>
                        <label htmlFor="societyName" className="block text-sm font-semibold text-gray-900 mb-2">
                          Society/Project Name <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="text"
                          id="societyName"
                          name="societyName"
                          placeholder="Enter society/project name"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.societyName && touched.societyName ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="societyName" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Society Code */}
                      <div>
                        <label htmlFor="societyCode" className="block text-sm font-semibold text-gray-900 mb-2">
                          Society Code <span className="text-red-500">*</span>
                        </label>
                        <div className="flex gap-2">
                          <Field
                            type="text"
                            id="societyCode"
                            name="societyCode"
                            placeholder="SOC-2024-001"
                            readOnly
                            className={`flex-1 px-4 py-3 border rounded-lg bg-gray-50 focus:outline-none ${
                              errors.societyCode && touched.societyCode ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <Button
                            type="button"
                            onClick={() => handleGenerateCode(setFieldValue)}
                            disabled={isGeneratingCode}
                            className="px-4 py-3"
                          >
                            {isGeneratingCode ? (
                              <Loader2 className="w-4 h-4 animate-spin" />
                            ) : (
                              <RefreshCw className="w-4 h-4" />
                            )}
                          </Button>
                        </div>
                        <ErrorMessage name="societyCode" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Logo Upload */}
                      <FileUploadField
                        name="logo"
                        label="Logo"
                        value={values.logo}
                        onChange={(file) => setFieldValue('logo', file)}
                        error={errors.logo as string}
                        touched={touched.logo}
                        required={mode === 'create'}
                        existingFileUrl={initialData?.logo}
                      />
                    </div>

                    {/* Description */}
                    <div>
                      <label htmlFor="description" className="block text-sm font-semibold text-gray-900 mb-2">
                        Description/Notes <span className="text-red-500">*</span>
                      </label>
                      <Field
                        as="textarea"
                        id="description"
                        name="description"
                        rows={4}
                        placeholder="Enter description or notes..."
                        className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none ${
                          errors.description && touched.description ? 'border-red-500' : 'border-gray-300'
                        }`}
                      />
                      <ErrorMessage name="description" component="div" className="mt-1 text-sm text-red-500" />
                    </div>

                    <div className="flex justify-end">
                      <Button type="button" onClick={() => setActiveTab('project')}>
                        Next: Project Details
                      </Button>
                    </div>
                  </TabsContent>

                  {/* Tab 2: Project Details */}
                  <TabsContent value="project" className="space-y-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Project Details</h2>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      {/* Project Type */}
                      <div>
                        <label htmlFor="projectType" className="block text-sm font-semibold text-gray-900 mb-2">
                          Project Type <span className="text-red-500">*</span>
                        </label>
                        <Field
                          as="select"
                          id="projectType"
                          name="projectType"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.projectType && touched.projectType ? 'border-red-500' : 'border-gray-300'
                          }`}
                        >
                          <option value="Residential">Residential</option>
                          <option value="Commercial">Commercial</option>
                          <option value="Mixed Use">Mixed Use</option>
                        </Field>
                        <ErrorMessage name="projectType" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Units per Floor */}
                      <div>
                        <label htmlFor="totalUnits" className="block text-sm font-semibold text-gray-900 mb-2">
                          Units per Floor <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="number"
                          id="totalUnits"
                          name="totalUnits"
                          placeholder="Enter units per floor"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.totalUnits && touched.totalUnits ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="totalUnits" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Total Blocks */}
                      <div>
                        <label htmlFor="totalBlocks" className="block text-sm font-semibold text-gray-900 mb-2">
                          Total Blocks <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="number"
                          id="totalBlocks"
                          name="totalBlocks"
                          placeholder="Enter total blocks"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.totalBlocks && touched.totalBlocks ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="totalBlocks" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Total Floors */}
                      <div>
                        <label htmlFor="totalFloors" className="block text-sm font-semibold text-gray-900 mb-2">
                          Total Floors <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="number"
                          id="totalFloors"
                          name="totalFloors"
                          placeholder="Enter total floors"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.totalFloors && touched.totalFloors ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="totalFloors" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Carpet Area Range */}
                      <div>
                        <label htmlFor="carpetAreaRange" className="block text-sm font-semibold text-gray-900 mb-2">
                          Carpet Area Range <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="text"
                          id="carpetAreaRange"
                          name="carpetAreaRange"
                          placeholder="e.g., 500-1200 sq ft"
                          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                      </div>

                      {/* Developer Name */}
                      <div>
                        <label htmlFor="developerName" className="block text-sm font-semibold text-gray-900 mb-2">
                          Developer/Builder Name <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="text"
                          id="developerName"
                          name="developerName"
                          placeholder="Enter developer name"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.developerName && touched.developerName ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="developerName" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Project Start Date */}
                      <div>
                        <label htmlFor="projectStartDate" className="block text-sm font-semibold text-gray-900 mb-2">
                          Project Start Date <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="date"
                          id="projectStartDate"
                          name="projectStartDate"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.projectStartDate && touched.projectStartDate ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="projectStartDate" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Completion Date */}
                      <div>
                        <label htmlFor="completionDate" className="block text-sm font-semibold text-gray-900 mb-2">
                          Expected/Actual Completion Date <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="date"
                          id="completionDate"
                          name="completionDate"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.completionDate && touched.completionDate ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="completionDate" component="div" className="mt-1 text-sm text-red-500" />
                      </div>
                    </div>

                    <div className="flex justify-between">
                      <Button type="button" variant="outline" onClick={() => setActiveTab('basic')}>
                        Previous
                      </Button>
                      <Button type="button" onClick={() => setActiveTab('contact')}>
                        Next: Contact Details
                      </Button>
                    </div>
                  </TabsContent>

                  {/* Tab 3: Contact Information */}
                  <TabsContent value="contact" className="space-y-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Information</h2>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      {/* Contact Person Name */}
                      <div>
                        <label htmlFor="contactPersonName" className="block text-sm font-semibold text-gray-900 mb-2">
                          Contact Person Name <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="text"
                          id="contactPersonName"
                          name="contactPersonName"
                          placeholder="Enter contact person name"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.contactPersonName && touched.contactPersonName ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="contactPersonName" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Contact Number */}
                      <div>
                        <label htmlFor="contactNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                          Contact Number <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="tel"
                          id="contactNumber"
                          name="contactNumber"
                          placeholder="Enter 10-digit mobile number"
                          maxLength={10}
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.contactNumber && touched.contactNumber ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="contactNumber" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Email */}
                      <div>
                        <label htmlFor="email" className="block text-sm font-semibold text-gray-900 mb-2">
                          Email Address <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="email"
                          id="email"
                          name="email"
                          placeholder="Enter email address"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.email && touched.email ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="email" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Alternate Contact */}
                      <div>
                        <label htmlFor="alternateContact" className="block text-sm font-semibold text-gray-900 mb-2">
                          Alternate Contact Number <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="tel"
                          id="alternateContact"
                          name="alternateContact"
                          placeholder="Enter alternate number"
                          maxLength={10}
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.alternateContact && touched.alternateContact ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="alternateContact" component="div" className="mt-1 text-sm text-red-500" />
                      </div>
                    </div>

                    {/* Address */}
                    <div>
                      <label htmlFor="address" className="block text-sm font-semibold text-gray-900 mb-2">
                        Complete Address <span className="text-red-500">*</span>
                      </label>
                      <Field
                        as="textarea"
                        id="address"
                        name="address"
                        rows={3}
                        placeholder="Enter complete address"
                        className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none ${
                          errors.address && touched.address ? 'border-red-500' : 'border-gray-300'
                        }`}
                      />
                      <ErrorMessage name="address" component="div" className="mt-1 text-sm text-red-500" />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                      {/* City */}
                      <div>
                        <label htmlFor="city" className="block text-sm font-semibold text-gray-900 mb-2">
                          City <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="text"
                          id="city"
                          name="city"
                          placeholder="Enter city"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.city && touched.city ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="city" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* State */}
                      <div>
                        <label htmlFor="state" className="block text-sm font-semibold text-gray-900 mb-2">
                          State <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="text"
                          id="state"
                          name="state"
                          placeholder="Enter state"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.state && touched.state ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="state" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Pincode */}
                      <div>
                        <label htmlFor="pincode" className="block text-sm font-semibold text-gray-900 mb-2">
                          Pincode <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="text"
                          id="pincode"
                          name="pincode"
                          placeholder="Enter 6-digit pincode"
                          maxLength={6}
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.pincode && touched.pincode ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="pincode" component="div" className="mt-1 text-sm text-red-500" />
                      </div>
                    </div>

                    <div className="flex justify-between">
                      <Button type="button" variant="outline" onClick={() => setActiveTab('project')}>
                        Previous
                      </Button>
                      <Button type="button" onClick={() => setActiveTab('legal')}>
                        Next: Legal Documents
                      </Button>
                    </div>
                  </TabsContent>

                  {/* Tab 4: Legal Documents - Continue in part 2*/}
                  <TabsContent value="legal" className="space-y-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Legal Documents</h2>
                    
                    {/* RERA Details */}
                    <div className="p-6 bg-gray-50 rounded-lg space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900">RERA Details</h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label htmlFor="reraNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                            RERA Number <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="reraNumber"
                            name="reraNumber"
                            placeholder="Enter RERA number"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div>
                          <label htmlFor="reraExpiryDate" className="block text-sm font-semibold text-gray-900 mb-2">
                            RERA Expiry Date <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="date"
                            id="reraExpiryDate"
                            name="reraExpiryDate"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div className="md:col-span-2">
                          <FileUploadField
                            name="reraCertificate"
                            label="RERA Certificate"
                            value={values.reraCertificate}
                            onChange={(file) => setFieldValue('reraCertificate', file)}
                            error={errors.reraCertificate as string}
                            touched={touched.reraCertificate}
                            required={mode === 'create'}
                            existingFileUrl={initialData?.legalDocuments?.rera?.certificate}
                          />
                        </div>
                      </div>
                    </div>

                    {/* Fire NOC */}
                    <div className="p-6 bg-gray-50 rounded-lg space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900">Fire NOC</h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label htmlFor="fireNocNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                            Fire NOC Number <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="fireNocNumber"
                            name="fireNocNumber"
                            placeholder="Enter Fire NOC number"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div>
                          <label htmlFor="fireNocValidityDate" className="block text-sm font-semibold text-gray-900 mb-2">
                            Fire NOC Validity Date <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="date"
                            id="fireNocValidityDate"
                            name="fireNocValidityDate"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div className="md:col-span-2">
                          <FileUploadField
                            name="fireNocDocument"
                            label="Fire NOC Document"
                            value={values.fireNocDocument}
                            onChange={(file) => setFieldValue('fireNocDocument', file)}
                            error={errors.fireNocDocument as string}
                            touched={touched.fireNocDocument}
                            required={mode === 'create'}
                            existingFileUrl={initialData?.legalDocuments?.fireNoc?.document}
                          />
                        </div>
                      </div>
                    </div>

                    {/* Building Use Certificate */}
                    <div className="p-6 bg-gray-50 rounded-lg space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900">Building Use (BU) Certificate</h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label htmlFor="buCertificateNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                            BU Certificate Number <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="buCertificateNumber"
                            name="buCertificateNumber"
                            placeholder="Enter BU certificate number"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div>
                          <label htmlFor="buIssueDate" className="block text-sm font-semibold text-gray-900 mb-2">
                            BU Issue Date <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="date"
                            id="buIssueDate"
                            name="buIssueDate"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div className="md:col-span-2">
                          <FileUploadField
                            name="buCertificate"
                            label="BU Certificate"
                            value={values.buCertificate}
                            onChange={(file) => setFieldValue('buCertificate', file)}
                            error={errors.buCertificate as string}
                            touched={touched.buCertificate}
                            required={mode === 'create'}
                            existingFileUrl={initialData?.legalDocuments?.buCertificate?.certificate}
                          />
                        </div>
                      </div>
                    </div>

                    {/* Lift Licence */}
                    <div className="p-6 bg-gray-50 rounded-lg space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900">Lift Licence</h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label htmlFor="liftLicenceNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                            Lift Licence Number <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="liftLicenceNumber"
                            name="liftLicenceNumber"
                            placeholder="Enter lift licence number"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div>
                          <label htmlFor="liftLicenceExpiryDate" className="block text-sm font-semibold text-gray-900 mb-2">
                            Lift Licence Expiry Date <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="date"
                            id="liftLicenceExpiryDate"
                            name="liftLicenceExpiryDate"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div className="md:col-span-2">
                          <FileUploadField
                            name="liftLicenceDocument"
                            label="Lift Licence Document"
                            value={values.liftLicenceDocument}
                            onChange={(file) => setFieldValue('liftLicenceDocument', file)}
                            error={errors.liftLicenceDocument as string}
                            touched={touched.liftLicenceDocument}
                            required={mode === 'create'}
                            existingFileUrl={initialData?.legalDocuments?.liftLicence?.document}
                          />
                        </div>
                      </div>
                    </div>

                    <div className="flex justify-between">
                      <Button type="button" variant="outline" onClick={() => setActiveTab('contact')}>
                        Previous
                      </Button>
                      <Button type="button" onClick={() => setActiveTab('financial')}>
                        Next: Financial Setup
                      </Button>
                    </div>
                  </TabsContent>

                  {/* Tab 5: Financial Setup */}
                  <TabsContent value="financial" className="space-y-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Financial Setup</h2>
                    
                    {/* Bank Details */}
                    <div className="p-6 bg-gray-50 rounded-lg space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900">Bank Details</h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label htmlFor="bankName" className="block text-sm font-semibold text-gray-900 mb-2">
                            Bank Name <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="bankName"
                            name="bankName"
                            placeholder="Enter bank name"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.bankName && touched.bankName ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <ErrorMessage name="bankName" component="div" className="mt-1 text-sm text-red-500" />
                        </div>

                        <div>
                          <label htmlFor="accountNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                            Account Number <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="accountNumber"
                            name="accountNumber"
                            placeholder="Enter account number"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.accountNumber && touched.accountNumber ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <ErrorMessage name="accountNumber" component="div" className="mt-1 text-sm text-red-500" />
                        </div>

                        <div>
                          <label htmlFor="accountHolderName" className="block text-sm font-semibold text-gray-900 mb-2">
                            Account Holder Name <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="accountHolderName"
                            name="accountHolderName"
                            placeholder="Enter account holder name"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.accountHolderName && touched.accountHolderName ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <ErrorMessage name="accountHolderName" component="div" className="mt-1 text-sm text-red-500" />
                        </div>

                        <div>
                          <label htmlFor="ifscCode" className="block text-sm font-semibold text-gray-900 mb-2">
                            IFSC Code <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="ifscCode"
                            name="ifscCode"
                            placeholder="Enter IFSC code"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.ifscCode && touched.ifscCode ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <ErrorMessage name="ifscCode" component="div" className="mt-1 text-sm text-red-500" />
                        </div>

                        <div>
                          <label htmlFor="branchName" className="block text-sm font-semibold text-gray-900 mb-2">
                            Branch Name <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="branchName"
                            name="branchName"
                            placeholder="Enter branch name"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>

                        <div>
                          <label htmlFor="branchAddress" className="block text-sm font-semibold text-gray-900 mb-2">
                            Branch Address <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="branchAddress"
                            name="branchAddress"
                            placeholder="Enter branch address"
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                        </div>
                      </div>
                    </div>

                    {/* Tax Information */}
                    <div className="p-6 bg-gray-50 rounded-lg space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900">Tax Information</h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label htmlFor="gstNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                            GST Number <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="gstNumber"
                            name="gstNumber"
                            placeholder="Enter GST number"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.gstNumber && touched.gstNumber ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <ErrorMessage name="gstNumber" component="div" className="mt-1 text-sm text-red-500" />
                        </div>

                        <div>
                          <FileUploadField
                            name="gstCertificate"
                            label="GST Certificate"
                            value={values.gstCertificate}
                            onChange={(file) => setFieldValue('gstCertificate', file)}
                            error={errors.gstCertificate as string}
                            touched={touched.gstCertificate}
                            required={mode === 'create'}
                            existingFileUrl={initialData?.taxInformation?.gstCertificate}
                          />
                        </div>

                        <div>
                          <label htmlFor="panNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                            PAN Number <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="panNumber"
                            name="panNumber"
                            placeholder="Enter PAN number"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.panNumber && touched.panNumber ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <ErrorMessage name="panNumber" component="div" className="mt-1 text-sm text-red-500" />
                        </div>

                        <div>
                          <label htmlFor="tanNumber" className="block text-sm font-semibold text-gray-900 mb-2">
                            TAN Number <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="tanNumber"
                            name="tanNumber"
                            placeholder="Enter TAN number"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.tanNumber && touched.tanNumber ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <ErrorMessage name="tanNumber" component="div" className="mt-1 text-sm text-red-500" />
                        </div>
                      </div>
                    </div>

                    {/* Financial Year */}
                    <div className="p-6 bg-gray-50 rounded-lg space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900">Financial Year</h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label htmlFor="fyStartMonth" className="block text-sm font-semibold text-gray-900 mb-2">
                            FY Start Month <span className="text-red-500">*</span>
                          </label>
                          <Field
                            as="select"
                            id="fyStartMonth"
                            name="fyStartMonth"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.fyStartMonth && touched.fyStartMonth ? 'border-red-500' : 'border-gray-300'
                            }`}
                          >
                            {['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].map(month => (
                              <option key={month} value={month}>{month}</option>
                            ))}
                          </Field>
                          <ErrorMessage name="fyStartMonth" component="div" className="mt-1 text-sm text-red-500" />
                        </div>

                        <div>
                          <label htmlFor="currentFinancialYear" className="block text-sm font-semibold text-gray-900 mb-2">
                            Current Financial Year <span className="text-red-500">*</span>
                          </label>
                          <Field
                            type="text"
                            id="currentFinancialYear"
                            name="currentFinancialYear"
                            placeholder="e.g., 2024-2025"
                            className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                              errors.currentFinancialYear && touched.currentFinancialYear ? 'border-red-500' : 'border-gray-300'
                            }`}
                          />
                          <ErrorMessage name="currentFinancialYear" component="div" className="mt-1 text-sm text-red-500" />
                        </div>
                      </div>
                    </div>

                    <div className="flex justify-between">
                      <Button type="button" variant="outline" onClick={() => setActiveTab('legal')}>
                        Previous
                      </Button>
                      <Button type="button" onClick={() => setActiveTab('settings')}>
                        Next: Settings
                      </Button>
                    </div>
                  </TabsContent>

                  {/* Tab 6: Additional Settings */}
                  <TabsContent value="settings" className="space-y-6">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Additional Settings</h2>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      {/* Status */}
                      <div>
                        <label htmlFor="status" className="block text-sm font-semibold text-gray-900 mb-2">
                          Status <span className="text-red-500">*</span>
                        </label>
                        <Field
                          as="select"
                          id="status"
                          name="status"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.status && touched.status ? 'border-red-500' : 'border-gray-300'
                          }`}
                        >
                          <option value="Pending">Pending</option>
                          <option value="Active">Active</option>
                          <option value="Inactive">Inactive</option>
                        </Field>
                        <ErrorMessage name="status" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Maintenance Billing Cycle */}
                      <div>
                        <label htmlFor="maintenanceBillingCycle" className="block text-sm font-semibold text-gray-900 mb-2">
                          Maintenance Billing Cycle <span className="text-red-500">*</span>
                        </label>
                        <Field
                          as="select"
                          id="maintenanceBillingCycle"
                          name="maintenanceBillingCycle"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.maintenanceBillingCycle && touched.maintenanceBillingCycle ? 'border-red-500' : 'border-gray-300'
                          }`}
                        >
                          <option value="Monthly">Monthly</option>
                          <option value="Quarterly">Quarterly</option>
                          <option value="Yearly">Yearly</option>
                        </Field>
                        <ErrorMessage name="maintenanceBillingCycle" component="div" className="mt-1 text-sm text-red-500" />
                      </div>

                      {/* Registered Members Count */}
                      <div>
                        <label htmlFor="registeredMembersCount" className="block text-sm font-semibold text-gray-900 mb-2">
                          Registered Members Count <span className="text-red-500">*</span>
                        </label>
                        <Field
                          type="number"
                          id="registeredMembersCount"
                          name="registeredMembersCount"
                          placeholder="Enter count"
                          className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                            errors.registeredMembersCount && touched.registeredMembersCount ? 'border-red-500' : 'border-gray-300'
                          }`}
                        />
                        <ErrorMessage name="registeredMembersCount" component="div" className="mt-1 text-sm text-red-500" />
                      </div>
                    </div>

                    <div className="flex justify-between">
                      <Button type="button" variant="outline" onClick={() => setActiveTab('financial')}>
                        Previous
                      </Button>
                      <Button
                        type="submit"
                        disabled={isSubmitting}
                        className="bg-green-600 hover:bg-green-700 text-white"
                      >
                        {isSubmitting ? 'Submitting...' : 'Create Society/Project'}
                      </Button>
                    </div>
                  </TabsContent>
                </Tabs>
              </Form>
            )}
          </Formik>
        </div>
      </Card>
    </div>
  );
};
